# Generated by Django 6.1.1 on 2026-09-22 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cercado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "voltagem_cerca",
                    models.IntegerField(help_text="Voltagem atual em kV"),
                ),
                (
                    "dimensao",
                    models.CharField(
                        help_text="Dimensões do cercado (ex: 20x30m)", max_length=100
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Especie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                (
                    "dieta",
                    models.CharField(
                        choices=[
                            ("C", "Carnívoro"),
                            ("H", "Herbívoro"),
                            ("O", "Onívoro"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "nivel_periculosidade",
                    models.IntegerField(help_text="Escala de 1 a 10"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("pais_origem", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Dinossauro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nascimento", models.CharField(max_length=100)),
                (
                    "cercado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dinossauros",
                        to="api.cercado",
                    ),
                ),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dinossauros",
                        to="api.especie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cargo", models.CharField(max_length=100)),
                (
                    "funcionario_responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cercados",
                        to="api.cercado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carros",
                        to="api.marca",
                    ),
                ),
            ],
        ),
    ]
