# Generated by Django 6.1.1 on 2026-09-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carros', to='api.funcionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='tipo',
            field=models.CharField(choices=[('G', 'Guarda'), ('T', 'Turismo')], default='G', max_length=1),
            preserve_default=False,
        ),
    ]
