# Generated by Django 6.1.1 on 2026-09-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carro_funcionario_carro_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='preco',
        ),
    ]
