# Generated by Django 6.1.1 on 2026-09-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_carro_ano_remove_carro_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
