# Generated by Django 6.1.1 on 2026-09-28 17:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_carro_marca_delete_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(1980, 1, 1)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turistas', to='api.carro')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
