# Generated by Django 6.1.1 on 2026-09-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_funcionario_data_nascimento_turista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turista',
            name='documento',
        ),
    ]
