# Generated by Django 6.1.1 on 2026-09-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_turista_documento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turista',
        ),
    ]
